<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Expense extends Model
{
    use HasFactory, SoftDeletes;

    // Business-status constants — adjust if your actual enum values differ.
    public const STATUS_PENDING = 'Pending';
    public const STATUS_APPROVED = 'Approved';
    public const STATUS_REJECTED = 'Rejected';

    // Legal values per the DB check constraint (expenses_receipt_status_check)
    // — confirmed directly against Postgres, not assumed. 'Verified'/
    // 'Rejected' were never valid; RECEIPT_UPLOADED/RECEIPT_MISSING replace
    // what those constants used to (incorrectly) represent.
    public const RECEIPT_PENDING = 'Pending';
    public const RECEIPT_UPLOADED = 'Uploaded';
    public const RECEIPT_MISSING = 'Missing';

    // Legal values per the DB check constraint (expenses_expense_source_check)
    // — confirmed directly against Postgres. The frontend's free-text input
    // for this field was never actually free text; it just happened not to
    // fail until a value outside these three was entered.
    public const SOURCE_CASH = 'Cash';
    public const SOURCE_BANK = 'Bank';
    public const SOURCE_PETTY_CASH = 'Petty Cash';

    protected $fillable = [
        'budget_id',
        'expense_category_id',
        'supplier_id',
        'cash_account_id',
        'expense_date',
        'receipt_number',
        'expense_amount',
        'expense_source',
        'receipt_status',
        'description',
        'is_over_budget',
        'status',
        'rejection_remarks',
        'created_by',
        'approved_by',
        'approved_at',
        'rejected_by',
        'rejected_at',
    ];

    protected $casts = [
        'expense_date' => 'date',
        'expense_amount' => 'decimal:2',
        'is_over_budget' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
        'approved_at' => 'datetime',
        'rejected_at' => 'datetime',
    ];

    // Mirrors Budget's $appends = ['has_plan'] pattern exactly — has_receipt
    // is what the React row actions read to decide "Attach" vs "View/History".
    protected $appends = ['has_receipt'];

    protected static function booted(): void
    {
        // deleted_by isn't touched automatically by SoftDeletes, so we
        // stamp it right before the delete actually happens.
        static::deleting(function (Expense $expense) {
            if (! $expense->isForceDeleting()) {
                $expense->deleted_by = Auth::id();
                $expense->saveQuietly();
            }
        });
    }

    public function budget(): BelongsTo
    {
        return $this->belongsTo(Budget::class);
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(ExpenseCategory::class, 'expense_category_id');
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Supplier::class);
    }

    public function cashAccount(): BelongsTo
    {
        return $this->belongsTo(CashAccount::class);
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function deleter(): BelongsTo
    {
        return $this->belongsTo(User::class, 'deleted_by');
    }

    public function approver(): BelongsTo
    {
        return $this->belongsTo(User::class, 'approved_by');
    }

    public function rejector(): BelongsTo
    {
        return $this->belongsTo(User::class, 'rejected_by');
    }

    /**
     * Tax obligations traced back to this expense (e.g. withholding tax
     * generated by this specific spend). expense_id is nullable on
     * tax_obligations, so not every expense will have any — this is for
     * display/traceability on the expense detail view, not something
     * every expense is expected to have.
     */
    public function taxObligations(): HasMany
    {
        return $this->hasMany(TaxObligation::class);
    }

    /**
     * Receipt/document files attached to this expense, via the shared
     * supporting_documents table (reference_type = 'expense') — same
     * mechanism Budget uses for plan uploads and Collection uses for
     * proof-of-receipt (reference_type = 'budget' / 'collection'
     * respectively). Each module only ever queries its own
     * reference_type back; there's no cross-module fetching here.
     */
    public function supportingDocuments(): HasMany
    {
        return $this->hasMany(SupportingDocument::class, 'reference_id')
            ->where('reference_type', 'expense');
    }

    /**
     * Whether a receipt has been attached. Mirrors Budget's
     * getHasPlanAttribute() exactly, including the same N+1 warning:
     * calling this in a loop over many expenses (e.g. the index listing)
     * will N+1 — callers that list many expenses should eager-load
     * withCount('supportingDocuments as supporting_documents_count')
     * instead of relying on this accessor directly, the same way
     * BudgetService::forApprovalList() does for budgets.
     */
    public function getHasReceiptAttribute(): bool
    {
        if (array_key_exists('supporting_documents_count', $this->attributes)) {
            return ((int) $this->attributes['supporting_documents_count']) > 0;
        }

        return $this->supportingDocuments()->exists();
    }

    public function scopeSearch(Builder $query, ?string $term): Builder
    {
        if (! $term) {
            return $query;
        }

        return $query->where(function (Builder $q) use ($term) {
            $q->where('description', 'ilike', "%{$term}%")
                ->orWhere('receipt_number', 'ilike', "%{$term}%")
                ->orWhere('expense_source', 'ilike', "%{$term}%");
        });
    }

    public function scopeStatus(Builder $query, ?string $status): Builder
    {
        return $status ? $query->where('status', $status) : $query;
    }

    public function scopeForBudget(Builder $query, ?int $budgetId): Builder
    {
        return $budgetId ? $query->where('budget_id', $budgetId) : $query;
    }

    public function scopeForCategory(Builder $query, ?int $categoryId): Builder
    {
        return $categoryId ? $query->where('expense_category_id', $categoryId) : $query;
    }

    /**
     * Filters by expense_date within an inclusive [from, to] range.
     * Either bound can be omitted; passing neither is a no-op.
     */
    public function scopeExpenseDateBetween(Builder $query, ?string $from, ?string $to): Builder
    {
        if ($from) {
            $query->whereDate('expense_date', '>=', $from);
        }

        if ($to) {
            $query->whereDate('expense_date', '<=', $to);
        }

        return $query;
    }
}