<?php

namespace Database\Seeders;

use App\Models\AccountsReceivable;
use App\Models\Customer;
use App\Models\User;
use Illuminate\Database\Seeder;

/**
 * Seeds sample Accounts Receivable invoices across 6 months of historical data (April - September 2026).
 * Provides authentic, high-fidelity transactions for ARIMA AI forecasting and defense demonstrations.
 */
class AccountsReceivableSeeder extends Seeder
{
    public function run(): void
    {
        $customers = Customer::all();
        $users = User::all();

        if ($customers->isEmpty()) {
            $this->command->warn('No customers found — skipping AccountsReceivableSeeder. Seed customers first.');
            return;
        }

        if ($users->isEmpty()) {
            $this->command->warn('No users found — skipping AccountsReceivableSeeder. Seed users first.');
            return;
        }

        $customer = fn (int $i) => $customers[$i % $customers->count()];
        $user = fn (int $i) => $users[$i % $users->count()];

        $rows = [
            // Month 1: April 2026
            [
                'invoice_number' => 'INV-2026-0401',
                'invoice_date' => '2026-04-05',
                'due_date' => '2026-05-05',
                'original_amount' => 240000.00,
                'balance' => 0.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-MW-2026-041',
                'reference_no' => 'REF-AR-0401',
                'penalty_rate' => 0,
                'remarks' => 'Metro Manila Subway Phase 1 crane rental mobilization - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0402',
                'invoice_date' => '2026-04-12',
                'due_date' => '2026-05-12',
                'original_amount' => 185000.00,
                'balance' => 0.00,
                'payment_method' => 'Check',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-DM-2026-019',
                'reference_no' => 'REF-AR-0402',
                'penalty_rate' => 0,
                'remarks' => 'North Luzon Expressway girder lifting and positioning - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0403',
                'invoice_date' => '2026-04-20',
                'due_date' => '2026-05-20',
                'original_amount' => 310000.00,
                'balance' => 0.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-EE-2026-088',
                'reference_no' => 'REF-AR-0403',
                'penalty_rate' => 0,
                'remarks' => 'Skyway Stage 4 precast beam hauling and erection - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0404',
                'invoice_date' => '2026-04-27',
                'due_date' => '2026-05-27',
                'original_amount' => 95000.00,
                'balance' => 0.00,
                'payment_method' => 'Cash',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-SMC-2026-012',
                'reference_no' => 'REF-AR-0404',
                'penalty_rate' => 0,
                'remarks' => 'Bulacan Airport access roadway gravel hauling - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],

            // Month 2: May 2026
            [
                'invoice_number' => 'INV-2026-0501',
                'invoice_date' => '2026-05-04',
                'due_date' => '2026-06-04',
                'original_amount' => 275000.00,
                'balance' => 0.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-PM-2026-033',
                'reference_no' => 'REF-AR-0501',
                'penalty_rate' => 0,
                'remarks' => 'Wawa Bulk Water Treatment structural erection - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0502',
                'invoice_date' => '2026-05-14',
                'due_date' => '2026-06-14',
                'original_amount' => 140000.00,
                'balance' => 0.00,
                'payment_method' => 'Check',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-MDC-2026-055',
                'reference_no' => 'REF-AR-0502',
                'penalty_rate' => 0,
                'remarks' => 'Arca South Tower commercial HVAC equipment hoisting - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0503',
                'invoice_date' => '2026-05-21',
                'due_date' => '2026-06-21',
                'original_amount' => 380000.00,
                'balance' => 0.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-FB-2026-102',
                'reference_no' => 'REF-AR-0503',
                'penalty_rate' => 0,
                'remarks' => 'Bataan-Cavite Interlink geotechnical sounding crane rig - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0504',
                'invoice_date' => '2026-05-28',
                'due_date' => '2026-06-28',
                'original_amount' => 120000.00,
                'balance' => 0.00,
                'payment_method' => 'Check',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-SC-2026-044',
                'reference_no' => 'REF-AR-0504',
                'penalty_rate' => 0,
                'remarks' => 'MRT-7 Station 4 steel truss assembly lifting - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],

            // Month 3: June 2026
            [
                'invoice_number' => 'INV-2026-0601',
                'invoice_date' => '2026-06-03',
                'due_date' => '2026-07-03',
                'original_amount' => 295000.00,
                'balance' => 0.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-MW-2026-062',
                'reference_no' => 'REF-AR-0601',
                'penalty_rate' => 0,
                'remarks' => 'Malolos-Clark Railway Project heavy piling and crane rig - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0602',
                'invoice_date' => '2026-06-11',
                'due_date' => '2026-07-11',
                'original_amount' => 165000.00,
                'balance' => 0.00,
                'payment_method' => 'Check',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-SL-2026-015',
                'reference_no' => 'REF-AR-0602',
                'penalty_rate' => 0,
                'remarks' => 'North-South Commuter Railway precast segment installation - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0603',
                'invoice_date' => '2026-06-18',
                'due_date' => '2026-07-18',
                'original_amount' => 210000.00,
                'balance' => 50000.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-AC-2026-077',
                'reference_no' => 'REF-AR-0603',
                'penalty_rate' => 2.0,
                'remarks' => 'C5 Southlink Expressway segmental bridge installation - Partial settlement',
                'status' => 'Partially Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0604',
                'invoice_date' => '2026-06-26',
                'due_date' => '2026-07-26',
                'original_amount' => 88000.00,
                'balance' => 88000.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-CC-2026-029',
                'reference_no' => 'REF-AR-0604',
                'penalty_rate' => 2.5,
                'remarks' => 'Subic Free Harbor container gantry emergency repair lift - Overdue notice sent',
                'status' => 'Overdue',
                'is_archived' => false,
            ],

            // Month 4: July 2026
            [
                'invoice_number' => 'INV-2026-0701',
                'invoice_date' => '2026-07-02',
                'due_date' => '2026-08-02',
                'original_amount' => 320000.00,
                'balance' => 0.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-DM-2026-048',
                'reference_no' => 'REF-AR-0701',
                'penalty_rate' => 0,
                'remarks' => 'CALAX Expressway interchange flyover pier cap lift - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0702',
                'invoice_date' => '2026-07-09',
                'due_date' => '2026-08-09',
                'original_amount' => 195000.00,
                'balance' => 0.00,
                'payment_method' => 'Check',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-MW-2026-089',
                'reference_no' => 'REF-AR-0702',
                'penalty_rate' => 0,
                'remarks' => 'Cavitex C5 Extension heavy lowbed transport - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0703',
                'invoice_date' => '2026-07-16',
                'due_date' => '2026-08-16',
                'original_amount' => 260000.00,
                'balance' => 60000.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-EE-2026-112',
                'reference_no' => 'REF-AR-0703',
                'penalty_rate' => 0,
                'remarks' => 'Bataan LNG Terminal piping module hoisting - Progress retention',
                'status' => 'Partially Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0704',
                'invoice_date' => '2026-07-23',
                'due_date' => '2026-08-23',
                'original_amount' => 110000.00,
                'balance' => 110000.00,
                'payment_method' => 'Check',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-PM-2026-061',
                'reference_no' => 'REF-AR-0704',
                'penalty_rate' => 2.0,
                'remarks' => 'North Harbor container crane support legs hauling - Collections follow-up',
                'status' => 'Overdue',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0705',
                'invoice_date' => '2026-07-30',
                'due_date' => '2026-08-30',
                'original_amount' => 78000.00,
                'balance' => 0.00,
                'payment_method' => 'Cash',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-SC-2026-071',
                'reference_no' => 'REF-AR-0705',
                'penalty_rate' => 0,
                'remarks' => 'Makati CBD building generator replacement lift - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],

            // Month 5: August 2026
            [
                'invoice_number' => 'INV-2026-0801',
                'invoice_date' => '2026-08-03',
                'due_date' => '2026-09-03',
                'original_amount' => 345000.00,
                'balance' => 0.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-SMC-2026-058',
                'reference_no' => 'REF-AR-0801',
                'penalty_rate' => 0,
                'remarks' => 'SMC Mass Rail Transit 7 girder deployment - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0802',
                'invoice_date' => '2026-08-10',
                'due_date' => '2026-09-10',
                'original_amount' => 215000.00,
                'balance' => 55000.00,
                'payment_method' => 'Check',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-MDC-2026-092',
                'reference_no' => 'REF-AR-0802',
                'penalty_rate' => 0,
                'remarks' => 'Ayala Triangle Tower Two transformer hoisting - Milestone billing',
                'status' => 'Partially Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0803',
                'invoice_date' => '2026-08-17',
                'due_date' => '2026-09-17',
                'original_amount' => 175000.00,
                'balance' => 175000.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-FB-2026-140',
                'reference_no' => 'REF-AR-0803',
                'penalty_rate' => 2.0,
                'remarks' => 'Subic Bay Freeport yard drydock crane support - Overdue',
                'status' => 'Overdue',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0804',
                'invoice_date' => '2026-08-22',
                'due_date' => '2026-09-22',
                'original_amount' => 290000.00,
                'balance' => 0.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-SL-2026-042',
                'reference_no' => 'REF-AR-0804',
                'penalty_rate' => 0,
                'remarks' => 'SLEX Tollway elevated widening span 12 lift - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0805',
                'invoice_date' => '2026-08-28',
                'due_date' => '2026-09-28',
                'original_amount' => 135000.00,
                'balance' => 65000.00,
                'payment_method' => 'Check',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-AC-2026-105',
                'reference_no' => 'REF-AR-0805',
                'penalty_rate' => 0,
                'remarks' => 'Bataan Petrochemical plant cooling tower assembly - Partial settlement',
                'status' => 'Partially Paid',
                'is_archived' => false,
            ],

            // Month 6: September 2026
            [
                'invoice_number' => 'INV-2026-0901',
                'invoice_date' => '2026-09-02',
                'due_date' => '2026-10-02',
                'original_amount' => 360000.00,
                'balance' => 0.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-MW-2026-120',
                'reference_no' => 'REF-AR-0901',
                'penalty_rate' => 0,
                'remarks' => 'Clark International Airport cargo hub girder installation - Paid in full',
                'status' => 'Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0902',
                'invoice_date' => '2026-09-08',
                'due_date' => '2026-10-08',
                'original_amount' => 225000.00,
                'balance' => 225000.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-DM-2026-079',
                'reference_no' => 'REF-AR-0902',
                'penalty_rate' => 0,
                'remarks' => 'LRT-1 Cavite Extension viaduct segment hauling - Under review',
                'status' => 'Pending',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0903',
                'invoice_date' => '2026-09-14',
                'due_date' => '2026-10-14',
                'original_amount' => 190000.00,
                'balance' => 95000.00,
                'payment_method' => 'Check',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-EE-2026-150',
                'reference_no' => 'REF-AR-0903',
                'penalty_rate' => 0,
                'remarks' => 'Batangas Port expansion heavy equipment crawler mobilization - Partial downpayment',
                'status' => 'Partially Paid',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0904',
                'invoice_date' => '2026-09-20',
                'due_date' => '2026-10-20',
                'original_amount' => 410000.00,
                'balance' => 410000.00,
                'payment_method' => 'Bank Transfer',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-PM-2026-088',
                'reference_no' => 'REF-AR-0904',
                'penalty_rate' => 0,
                'remarks' => 'Manila Bay reclamation rock revetment heavy grab crane - Pending approval',
                'status' => 'Pending',
                'is_archived' => false,
            ],
            [
                'invoice_number' => 'INV-2026-0905',
                'invoice_date' => '2026-09-25',
                'due_date' => '2026-10-25',
                'original_amount' => 145000.00,
                'balance' => 145000.00,
                'payment_method' => 'Check',
                'payment_terms' => 'Net 30',
                'purchase_order_no' => 'PO-SMC-2026-090',
                'reference_no' => 'REF-AR-0905',
                'penalty_rate' => 0,
                'remarks' => 'Pasig River Expressway pier foundations trial lifting - Fresh billing',
                'status' => 'Pending',
                'is_archived' => false,
            ],
        ];

        foreach ($rows as $i => $row) {
            $creator = $user($i);
            $penaltyAmount = $row['penalty_rate'] > 0
                ? round(($row['original_amount'] * $row['penalty_rate']) / 100, 2)
                : 0;

            AccountsReceivable::updateOrCreate(
                ['invoice_number' => $row['invoice_number']],
                [
                    'customer_id' => $customer($i)->id,
                    'invoice_date' => $row['invoice_date'],
                    'due_date' => $row['due_date'],
                    'original_amount' => $row['original_amount'],
                    'paid_amount' => max(0, $row['original_amount'] - $row['balance']),
                    'remaining_balance' => $row['balance'],
                    'payment_method' => $row['payment_method'],
                    'payment_terms' => $row['payment_terms'],
                    'purchase_order_no' => $row['purchase_order_no'],
                    'reference_no' => $row['reference_no'],
                    'penalty_rate' => $row['penalty_rate'],
                    'penalty_amount' => $penaltyAmount,
                    'remarks' => $row['remarks'],
                    'status' => $row['status'],
                    'created_by' => $creator->id,
                    'is_archived' => $row['is_archived'],
                    'archived_at' => $row['is_archived'] ? now() : null,
                    'archived_by' => $row['is_archived'] ? $creator->id : null,
                ]
            );
        }

        $this->command?->info('Seeded ' . count($rows) . ' accounts receivable records across 6 months.');
    }
}