<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            [
                'customer_name'   => 'Megawide Construction Corporation',
                'contact_person'  => 'Engr. Manuel Alcantara',
                'contact_number'  => '0917 882 1450',
                'email'           => 'procurement@megawide.com.ph',
                'address'         => 'No. 20 M. De Leon St., Santolan, Pasig City',
                'tin'             => '004-771-829-000',
                'industry'        => 'Heavy Civil & Transit Infrastructure',
                'credit_limit'    => 5000000.00,
                'payment_terms'   => 'Net 30',
                'contract_ref'    => 'MSA-2026-MGW-001',
                'contract_expiry' => '2027-12-31',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'DMCI Holdings Heavy Projects Inc.',
                'contact_person'  => 'Arch. Roberto Consunji',
                'contact_number'  => '0918 334 9912',
                'email'           => 'billing@dmci.com.ph',
                'address'         => 'DMCI Plaza, 2281 Chino Roces Ave., Makati City',
                'tin'             => '000-884-219-000',
                'industry'        => 'Commercial High-Rise & Highway Rigging',
                'credit_limit'    => 6000000.00,
                'payment_terms'   => 'Net 45',
                'contract_ref'    => 'MSA-2026-DMC-088',
                'contract_expiry' => '2027-06-30',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'EEI Corporation Industrial Division',
                'contact_person'  => 'Dennis Villafuerte',
                'contact_number'  => '0920 445 1102',
                'email'           => 'ap-logistics@eei.com.ph',
                'address'         => '12 Manggahan St., Bagumbayan, Quezon City',
                'tin'             => '000-992-310-000',
                'industry'        => 'Industrial Plant & Refinery Rigging',
                'credit_limit'    => 4500000.00,
                'payment_terms'   => 'Net 30',
                'contract_ref'    => 'MSA-2026-EEI-102',
                'contract_expiry' => '2027-03-31',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'San Miguel Infrastructure Logistics',
                'contact_person'  => 'Maria Cristina Co',
                'contact_number'  => '0917 555 7711',
                'email'           => 'smc.infra@sanmiguel.com.ph',
                'address'         => '40 San Miguel Ave., Mandaluyong City',
                'tin'             => '000-112-990-000',
                'industry'        => 'Expressway & Tollway Construction',
                'credit_limit'    => 8000000.00,
                'payment_terms'   => 'Net 60',
                'contract_ref'    => 'MSA-2025-SMC-041',
                'contract_expiry' => '2027-09-30',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'Prime Metroline Infrastructure Works',
                'contact_person'  => 'Victor Laurel',
                'contact_number'  => '0919 778 2233',
                'email'           => 'accounts@primemetroline.ph',
                'address'         => 'Bonifacio Global City, Taguig City',
                'tin'             => '102-334-556-000',
                'industry'        => 'Water & Energy Heavy Hauling',
                'credit_limit'    => 3500000.00,
                'payment_terms'   => 'Net 30',
                'contract_ref'    => 'MSA-2026-PMI-019',
                'contract_expiry' => '2026-12-31',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'Delacruz Trading & Construction',
                'contact_person'  => 'Juan Delacruz',
                'contact_number'  => '0917 234 5678',
                'email'           => 'accounts@delacruztrading.com',
                'address'         => 'Commonwealth Ave., Quezon City',
                'tin'             => '123-456-789-000',
                'industry'        => 'Commercial Construction',
                'credit_limit'    => 1200000.00,
                'payment_terms'   => 'Net 30',
                'contract_ref'    => 'MSA-2026-DT-012',
                'contract_expiry' => '2026-12-31',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'Meridian Industrial Warehousing Corp.',
                'contact_person'  => 'Liza Ramos',
                'contact_number'  => '0918 555 2211',
                'email'           => 'ap@meridianretail.com',
                'address'         => 'Legaspi Village, Makati City',
                'tin'             => '234-567-890-000',
                'industry'        => 'Industrial Logistics & Rigging',
                'credit_limit'    => 2000000.00,
                'payment_terms'   => 'Net 45',
                'contract_ref'    => 'MSA-2025-MRC-091',
                'contract_expiry' => '2027-01-31',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'Northgate Civil Infrastructure',
                'contact_person'  => 'Miguel Santos',
                'contact_number'  => '0920 112 3344',
                'email'           => 'finance@northgate.ph',
                'address'         => 'Cebu Business Park, Cebu City',
                'tin'             => '345-678-901-000',
                'industry'        => 'Bridge & Viaduct Erection',
                'credit_limit'    => 1800000.00,
                'payment_terms'   => 'Net 15',
                'contract_ref'    => 'MSA-2026-NT-004',
                'contract_expiry' => '2026-11-30',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'Bayview International Port Logistics',
                'contact_person'  => 'Carla Uy',
                'contact_number'  => '0921 987 6543',
                'email'           => 'billing@bayviewlog.com',
                'address'         => 'Sasa Port Commercial Complex, Davao City',
                'tin'             => '456-789-012-000',
                'industry'        => 'Harbor Cargo & Heavy Container Rigging',
                'credit_limit'    => 1500000.00,
                'payment_terms'   => 'Net 30',
                'contract_ref'    => 'MSA-2025-BL-019',
                'contract_expiry' => '2026-12-31',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'First Balfour Engineering Contractors',
                'contact_person'  => 'Engr. Gerald Aquino',
                'contact_number'  => '0917 662 9012',
                'email'           => 'gaquino@firstbalfour.com',
                'address'         => 'KM 19 West Service Rd., Sucat, Parañaque City',
                'tin'             => '678-901-234-000',
                'industry'        => 'Power Plant & Geothermal Rigging',
                'credit_limit'    => 4000000.00,
                'payment_terms'   => 'Net 30',
                'contract_ref'    => 'MSA-2026-FBC-031',
                'contract_expiry' => '2027-05-31',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'Atlantic Gulf & Pacific (AG&P) Heavy',
                'contact_person'  => 'Ramon Teodoro',
                'contact_number'  => '0918 442 8177',
                'email'           => 'rteodoro@agp.ph',
                'address'         => 'Bauan Heavy Fabrication Yard, Batangas',
                'tin'             => '789-012-345-000',
                'industry'        => 'Offshore Modular & Steel Rigging',
                'credit_limit'    => 7500000.00,
                'payment_terms'   => 'Net 60',
                'contract_ref'    => 'MSA-2025-AGP-007',
                'contract_expiry' => '2027-08-31',
                'status'          => 'Active',
            ],
            [
                'customer_name'   => 'Sierra Hardware & Quarry Supply',
                'contact_person'  => 'Tomas Cruz',
                'contact_number'  => '0917 444 0099',
                'email'           => 'sierra.hw@gmail.com',
                'address'         => 'Marcos Highway, Baguio City, Benguet',
                'tin'             => '567-890-123-000',
                'industry'        => 'Quarry Aggregate & Heavy Transport',
                'credit_limit'    => 500000.00,
                'payment_terms'   => 'Net 15',
                'contract_ref'    => 'MSA-2026-SH-001',
                'contract_expiry' => '2026-10-31',
                'status'          => 'Active',
            ],
        ];

        foreach ($customers as $data) {
            Customer::withTrashed()->updateOrCreate(
                ['email' => $data['email']],
                $data
            );
        }
    }
}