<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            [
                'supplier_name'           => 'Petron Corporation Fleet Solutions',
                'category'                => 'Diesel Fuel & Lubricants',
                'credit_limit'            => 1500000.00,
                'payment_terms'           => 'Net 30',
                'contract_ref'            => 'CTR-2026-PET-01',
                'contract_expiry'         => '2027-06-30',
                'contact_person'          => 'Eduardo Mendoza',
                'position'                => 'Corporate Fleet Accounts Head',
                'contact_number'          => '0917 888 1234',
                'email'                   => 'fleet.sales@petron.com',
                'website'                 => 'petron.com',
                'address'                 => 'Petron MegaPlaza, 358 Sen. Gil Puyat Ave., Makati City',
                'tin'                     => '000-168-801-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Goods',
            ],
            [
                'supplier_name'           => 'Pilipinas Shell Petroleum Bulk Supply',
                'category'                => 'Industrial Diesel & Engine Oil',
                'credit_limit'            => 1800000.00,
                'payment_terms'           => 'Net 30',
                'contract_ref'            => 'CTR-2026-SHL-04',
                'contract_expiry'         => '2027-04-30',
                'contact_person'          => 'Clarisse Dizon',
                'position'                => 'Commercial Fuels Manager',
                'contact_number'          => '0918 777 4321',
                'email'                   => 'commercialfuels@shell.com.ph',
                'website'                 => 'shell.com.ph',
                'address'                 => 'Shell House, 156 Valero St., Salcedo Village, Makati',
                'tin'                     => '000-164-756-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Goods',
            ],
            [
                'supplier_name'           => 'Monark Equipment Corporation (Caterpillar Dealer)',
                'category'                => 'Heavy Equipment Spare Parts & Service',
                'credit_limit'            => 2500000.00,
                'payment_terms'           => 'Net 45',
                'contract_ref'            => 'CTR-2025-MNK-09',
                'contract_expiry'         => '2027-12-31',
                'contact_person'          => 'Engr. Patrick Tan',
                'position'                => 'Parts & Product Support Director',
                'contact_number'          => '0917 222 9876',
                'email'                   => 'parts.support@monark-cat.com',
                'website'                 => 'monark-cat.com',
                'address'                 => '13 E. Rodriguez Jr. Ave., Bagumbayan, Quezon City',
                'tin'                     => '000-241-987-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Goods',
            ],
            [
                'supplier_name'           => 'Komatsu Philippines Heavy Parts Inc.',
                'category'                => 'Hydraulic Cranes & Excavator Components',
                'credit_limit'            => 2000000.00,
                'payment_terms'           => 'Net 30',
                'contract_ref'            => 'CTR-2026-KOM-12',
                'contract_expiry'         => '2027-08-31',
                'contact_person'          => 'Hiroshi Tanaka / Joel Bautista',
                'position'                => 'Regional Equipment Support Head',
                'contact_number'          => '0919 333 4567',
                'email'                   => 'service@komatsu.com.ph',
                'website'                 => 'komatsu.com.ph',
                'address'                 => 'Km. 23 West Service Rd., Cupang, Muntinlupa City',
                'tin'                     => '001-445-678-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Goods',
            ],
            [
                'supplier_name'           => 'Bridgestone Commercial Truck Tires Phils',
                'category'                => 'Commercial Heavy Truck Tires & Retreading',
                'credit_limit'            => 800000.00,
                'payment_terms'           => 'Net 30',
                'contract_ref'            => 'CTR-2026-BRG-07',
                'contract_expiry'         => '2026-12-31',
                'contact_person'          => 'Arman Dela Rosa',
                'position'                => 'Commercial Fleet Sales Executive',
                'contact_number'          => '0918 555 7890',
                'email'                   => 'fleettires@bridgestone.com.ph',
                'website'                 => 'bridgestone.com.ph',
                'address'                 => 'Chino Roces Ave. Ext., Makati City',
                'tin'                     => '000-889-112-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Goods',
            ],
            [
                'supplier_name'           => 'Pinnacle Freight & Heavy Hauling Co.',
                'category'                => 'Heavy Hauling & Subcontracting Services',
                'credit_limit'            => 1200000.00,
                'payment_terms'           => 'Net 15',
                'contract_ref'            => 'CTR-2025-PFC-11',
                'contract_expiry'         => '2026-11-30',
                'contact_person'          => 'Dennis Lim',
                'position'                => 'Logistics Operations Head',
                'contact_number'          => '0918 222 3344',
                'email'                   => 'billing@pinnaclefreight.com',
                'website'                 => 'pinnaclefreight.com',
                'address'                 => 'Mandaluyong City, Metro Manila',
                'tin'                     => '222-333-444-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Services',
            ],
            [
                'supplier_name'           => 'Coastal Steel & Rigging Supplies',
                'category'                => 'Wire Ropes, Shackles & Rigging Hardware',
                'credit_limit'            => 750000.00,
                'payment_terms'           => 'Net 45',
                'contract_ref'            => 'CTR-2026-CST-08',
                'contract_expiry'         => '2027-03-31',
                'contact_person'          => 'Marissa Ong',
                'position'                => 'Account Manager',
                'contact_number'          => '0920 333 4455',
                'email'                   => 'accounts@coastalsteel.ph',
                'website'                 => 'coastalsteel.ph',
                'address'                 => 'Iloilo Commercial Port Complex, Iloilo City',
                'tin'                     => '333-444-555-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Goods',
            ],
            [
                'supplier_name'           => 'Northgate Industrial Supplies Inc.',
                'category'                => 'Fleet Consumables & Hydraulic Filters',
                'credit_limit'            => 500000.00,
                'payment_terms'           => 'Net 30',
                'contract_ref'            => 'CTR-2026-NSI-02',
                'contract_expiry'         => '2026-11-30',
                'contact_person'          => 'Rico Alvarado',
                'position'                => 'Sales Director',
                'contact_number'          => '0917 111 2233',
                'email'                   => 'sales@northgatesupplies.com',
                'website'                 => 'northgatesupplies.com',
                'address'                 => 'Ortigas Ave., Pasig City',
                'tin'                     => '111-222-333-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Goods',
            ],
            [
                'supplier_name'           => 'Manila Hydraulic Seals & Hose Masters',
                'category'                => 'Hydraulic Hose Fabrication & Cylinders',
                'credit_limit'            => 400000.00,
                'payment_terms'           => 'Net 15',
                'contract_ref'            => 'CTR-2026-MHS-03',
                'contract_expiry'         => '2026-10-31',
                'contact_person'          => 'Danilo Macaraeg',
                'position'                => 'Technical Workshop Head',
                'contact_number'          => '0917 444 8811',
                'email'                   => 'service@manilahydraulics.ph',
                'website'                 => 'manilahydraulics.ph',
                'address'                 => 'Caloocan Industrial Zone, Caloocan City',
                'tin'                     => '445-556-667-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Services',
            ],
            [
                'supplier_name'           => 'Stronghold Heavy Fleet Insurance Corp.',
                'category'                => 'Commercial Vehicle & Crane Comprehensive Insurance',
                'credit_limit'            => 1000000.00,
                'payment_terms'           => 'Net 30',
                'contract_ref'            => 'POL-2026-SHI-88',
                'contract_expiry'         => '2027-01-31',
                'contact_person'          => 'Maria Lourdes Santos',
                'position'                => 'Senior Underwriting Officer',
                'contact_number'          => '0918 667 9001',
                'email'                   => 'fleet.underwriting@stronghold.com.ph',
                'website'                 => 'strongholdinsurance.com.ph',
                'address'                 => 'Ayala Ave., Makati City',
                'tin'                     => '000-556-112-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Services',
            ],
            [
                'supplier_name'           => 'Alliance Fuel Depot Misamis',
                'category'                => 'Regional Bulk Fuel & Depot Dispensing',
                'credit_limit'            => 450000.00,
                'payment_terms'           => 'Net 30',
                'contract_ref'            => 'CTR-2025-AFD-01',
                'contract_expiry'         => '2026-12-31',
                'contact_person'          => 'Gerald Sy',
                'position'                => 'Depot Supervisor',
                'contact_number'          => '0921 444 5566',
                'email'                   => 'ar@alliancefuel.com',
                'website'                 => null,
                'address'                 => 'Cagayan de Oro, Misamis Oriental',
                'tin'                     => '444-555-666-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Goods',
            ],
            [
                'supplier_name'           => 'Sunrise Office & Technology Depot',
                'category'                => 'Office Consumables, IT & Safety Supplies',
                'credit_limit'            => 200000.00,
                'payment_terms'           => 'Net 30',
                'contract_ref'            => 'PO-2026-SOD-05',
                'contract_expiry'         => '2026-12-31',
                'contact_person'          => 'Aina Cruz',
                'position'                => 'Key Accounts Officer',
                'contact_number'          => '0917 555 6677',
                'email'                   => 'orders@sunriseoffice.com',
                'website'                 => 'sunriseoffice.com',
                'address'                 => 'BGC, Taguig City, Metro Manila',
                'tin'                     => '555-666-777-000',
                'status'                  => 'Active',
                'default_withholding_type' => 'Goods',
            ],
        ];

        foreach ($suppliers as $data) {
            Supplier::withTrashed()->updateOrCreate(
                ['email' => $data['email']],
                $data
            );
        }
    }
}