import {
  LayoutDashboard,
  UserCog,
  ShieldCheck,
  Database,
  Users,
  Truck,
  UserCheck,
  Building2,
  Wallet,
  Boxes,
  ArrowLeftRight,
  FileText,
  HandCoins,
  FileMinus,
  Send,
  PiggyBank,
  Receipt,
  Landmark,
  BookOpen,
  BookText,
  LineChart,
  TrendingUp,
  Sparkles,
  FileBarChart,
  Settings,
  LogOut,
} from 'lucide-react'

// Each item: id, label, icon, path, and optional children for nested menus
export const menuData = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    path: '/dashboard',
  },
  {
    id: 'user-management',
    label: 'User Management',
    icon: UserCog,
    children: [
      { id: 'users', label: 'Users', icon: Users, path: '/user-management/users' },
      { id: 'roles', label: 'Roles', icon: ShieldCheck, path: '/user-management/roles' },
    ],
  },
  {
    id: 'master-data',
    label: 'Master Data',
    icon: Database,
    children: [
      { id: 'customers', label: 'Customers', icon: Users, path: '/master-data/customers' },
      { id: 'suppliers', label: 'Suppliers', icon: Truck, path: '/master-data/suppliers' },
      { id: 'collectors', label: 'Collectors', icon: UserCheck, path: '/master-data/collectors' },
      { id: 'departments', label: 'Departments', icon: Building2, path: '/master-data/departments' },
      { id: 'cash-accounts', label: 'Cash Accounts', icon: Wallet, path: '/master-data/cash-accounts' },
      { id: 'fixed-assets', label: 'Fixed Assets', icon: Boxes, path: '/master-data/fixed-assets' },
    ],
  },
  {
    id: 'financial-transactions',
    label: 'Financial Transactions',
    icon: ArrowLeftRight,
    children: [
      { id: 'ar', label: 'Accounts Receivable', icon: FileText, path: '/transactions/receivable' },
      { id: 'collections', label: 'Collections', icon: HandCoins, path: '/transactions/collections' },
      { id: 'ap', label: 'Accounts Payable', icon: FileMinus, path: '/transactions/payable' },
      { id: 'disbursements', label: 'Disbursements', icon: Send, path: '/transactions/disbursements' },
      { id: 'budgets', label: 'Budgets', icon: PiggyBank, path: '/transactions/budgets' },
      { id: 'expenses', label: 'Expenses', icon: Receipt, path: '/transactions/expenses' },
      { id: 'tax', label: 'Tax Obligations', icon: Landmark, path: '/transactions/tax-obligations' },
    ],
  },
  {
    id: 'accounting',
    label: 'Accounting',
    icon: BookOpen,
    children: [
      { id: 'general-ledger', label: 'General Ledger', icon: BookText, path: '/accounting/general-ledger' },
    ],
  },
  {
    id: 'analytics',
    label: 'Analytics',
    icon: LineChart,
    children: [
      { id: 'forecasting', label: 'Financial Forecasting', icon: TrendingUp, path: '/analytics/forecasting' },
      { id: 'ai', label: 'AI Financial Recommendations', icon: Sparkles, path: '/analytics/ai-recommendations' },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: FileBarChart,
    path: '/reports',
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings,
    path: '/settings',
  },
  {
    id: 'logout',
    label: 'Logout',
    icon: LogOut,
    path: '/logout',
    isLogout: true,
  },
]