// Shared renderer for the single-record "detail slip" documents.
//
// Six modules print the same shape of thing — one invoice, one receipt, one
// voucher, one tax record — as a two-column label/value table:
// AccountsPayable, AccountsReceivable, Budgets, Collections, Expenses and
// Taxobligations. Each used to hand-roll its own copy of the same HTML, CSS
// and window.print() call, which is how they drifted apart (and how the
// masked-amount bug ended up in all six).
//
// A slip is built declaratively here:
//
//   printSlip({
//     company, profile,
//     title: 'Official Receipt',
//     status: 'Paid',                      // renders a status badge
//     meta: [['OR Number', 'OR-0001']],    // right-hand header rows
//     groups: [
//       { heading: 'Collection Details', rows: [
//           ['Receipt Number', 'OR-0001'],
//           ['Amount Received', money(1234.5), 'total'],
//       ]},
//     ],
//     signatures: SIGNATURE_PRESETS.voucher({ ... }),
//   })
//
// Row value options (3rd element):
//   'total'  - emphasise as a figure row (double rule underneath)
//   'span'   - value starts at the label column instead of right-aligning
//   'muted'  - secondary/optional field, printed in grey
// A raw object { badge: 'Paid' } renders a status pill.

import { buildHeader, buildFooter, buildSignatureBlock, escapeHtml, printHtml, money } from './print'

/**
 * The user's display name and their job title, for the header's
 * "Generated By" row. ProfileResource exposes `role` (headlined) when the
 * relation is loaded, so fall back through the other title-ish fields rather
 * than printing a bare name.
 */
const profileTitle = (profile) =>
  profile?.role || profile?.role_slug || profile?.department || profile?.title || ''

/** Maps a module status string onto one of the shared badge styles. */
const badgeClass = (status = '') => {
  const s = String(status).toLowerCase()
  if (['paid', 'completed', 'approved', 'settled', 'filed', 'resolved'].includes(s)) return 'pf-badge-paid'
  if (['overdue', 'rejected', 'cancelled', 'void', 'written off', 'written-off'].includes(s)) return 'pf-badge-overdue'
  if (['pending', 'unpaid', 'partially paid', 'partially-paid', 'in progress', 'draft', 'submitted', 'escalated'].includes(s)) return 'pf-badge-pending'
  return 'pf-badge-neutral'
}

const renderValue = (value) => {
  if (value && typeof value === 'object' && value.badge !== undefined) {
    const text = value.badge || '—'
    return `<span class="pf-badge ${badgeClass(text)}">${escapeHtml(text)}</span>`
  }
  return escapeHtml(value === null || value === undefined || value === '' ? '—' : value)
}

const renderRow = ([label, value, opt = '']) => {
  const classes = ['pf-k', 'pf-v']
  if (opt === 'total') classes.push('pf-total')
  if (opt === 'muted') classes.push('pf-muted')
  const valueClass = opt === 'span' ? 'pf-v pf-span' : 'pf-v'
  return `<tr${opt === 'total' ? ' class="pf-total"' : ''}>
    <td class="pf-k">${escapeHtml(label)}</td>
    <td class="${valueClass}">${renderValue(value)}</td>
  </tr>`
}

const renderGroup = (group) => `
<table class="pf-kv">
  ${group.heading ? `<tr class="pf-section"><td colspan="2">${escapeHtml(group.heading)}</td></tr>` : ''}
  ${group.rows.map(renderRow).join('')}
</table>`

/**
 * Builds and prints a single-record detail slip.
 *
 * @param {object} o
 * @param {object} o.company        useCompany() value
 * @param {string} o.title          Document title (e.g. "Bill")
 * @param {string} o.subtitle       Under the title
 * @param {string} o.status         Status text for the header badge
 * @param {Array<[string,string]>} o.meta  Extra right-hand header rows
 * @param {Array} o.groups          Row groups (see module docblock)
 * @param {string} o.signatureTitle
 * @param {Array} o.signatures      Signature blocks
 * @param {string} o.footerNote
 * @param {string} o.disclaimer     Small print under the signature block
 * @param {string} o.spec           PAGE_SPECS name, e.g. 'bill' / 'receipt'
 * @param {object} o.printOptions   overrides for paper / orientation / margin / density
 * @returns {boolean} false when the popup was blocked
 */
export const printSlip = ({
  company,
  profile,
  title,
  subtitle = '',
  status = '',
  meta = [],
  groups = [],
  signatureTitle = 'Approval & Signatures',
  signatures = [],
  footerNote = '',
  disclaimer = '',
  spec,
  printOptions = {},
  onBeforePrint,
} = {}) => {
  const headerMeta = [
    ...meta,
    ...(status ? [['Status', status]] : []),
  ]

  const body = `
    ${buildHeader({
      company,
      title,
      subtitle,
      meta: headerMeta,
      preparedBy: profile?.name,
      preparedRole: profileTitle(profile),
    })}
    ${subtitle ? '' : ''}
    ${groups.map(renderGroup).join('<div style="height:4mm"></div>')}
    ${buildSignatureBlock({ title: signatureTitle, blocks: signatures })}
    ${disclaimer ? `<div class="pf-disclaimer">${escapeHtml(disclaimer)}</div>` : ''}
    ${buildFooter({ company, note: footerNote })}`

  return printHtml({
    title,
    body,
    company,
    ...(spec && { spec }),
    ...printOptions,
    onBeforePrint,
  })
}

export { money }
