<?php

namespace App\Console\Commands;

use App\Jobs\GenerateAiRecommendations;
use App\Models\FinancialForecast;
use App\Models\User;
use Illuminate\Console\Command;

/**
 * One-off backfill for forecasts that never got AI recommendations because
 * GenerateAiRecommendations::dispatch() only ever fires once, at forecast
 * creation time (see FinancialForecastService::generate()), and never
 * retries on its own. Forecasts created while either the forecast_period
 * 422 bug or the AI_ADVISOR_SERVICE_TOKEN 401 bug was live are permanently
 * stuck with zero recommendations unless re-dispatched manually — this
 * command does that.
 *
 * Usage:
 *   php artisan ai-recommendations:backfill
 *   php artisan ai-recommendations:backfill --dry-run
 *
 * Requires a queue worker running (php artisan queue:work) to actually
 * process the dispatched jobs, same as normal forecast generation — this
 * command only dispatches, it doesn't run the jobs synchronously.
 */
class BackfillAiRecommendations extends Command
{
    protected $signature = 'ai-recommendations:backfill {--dry-run : List affected forecasts without dispatching anything}';

    protected $description = 'Dispatch GenerateAiRecommendations for any active forecast that currently has zero recommendations';

    public function handle(): int
    {
        $forecasts = FinancialForecast::query()
            ->whereDoesntHave('aiRecommendations')
            ->with('generator')
            ->get();

        if ($forecasts->isEmpty()) {
            $this->info('Nothing to backfill — every forecast already has at least one recommendation.');
            return self::SUCCESS;
        }

        $this->info("Found {$forecasts->count()} forecast(s) with no recommendations:");
        $this->table(
            ['ID', 'Forecast No.', 'Type', 'Generated By', 'Generated At'],
            $forecasts->map(fn ($f) => [
                $f->id,
                $f->forecast_no,
                $f->forecast_type,
                $f->generator?->name ?? "User #{$f->generated_by}",
                $f->generated_at?->toDateTimeString(),
            ])
        );

        if ($this->option('dry-run')) {
            $this->comment('Dry run — no jobs dispatched.');
            return self::SUCCESS;
        }

        if (!$this->confirm('Dispatch GenerateAiRecommendations for all of these?', true)) {
            $this->comment('Cancelled.');
            return self::SUCCESS;
        }

        // generated_by is who requested the original forecast — reused
        // here as the actor for the recommendation job, since there's no
        // "system"/console user in this app and re-running this on behalf
        // of whoever originally asked for the forecast is the closest
        // honest attribution available.
        foreach ($forecasts as $forecast) {
            GenerateAiRecommendations::dispatch($forecast, $forecast->generated_by);
        }

        $this->info("Dispatched {$forecasts->count()} job(s). Make sure `php artisan queue:work` is running to process them.");

        return self::SUCCESS;
    }
}