<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dashboard Summary</title>
    <style>
        /* dompdf has limited CSS support  -  keep this simple: no flexbox/grid. */
        /* A4 portrait. Margins mirror the 'snapshot' PAGE_SPEC in
           finance-frontend/src/utils/print.js (14mm top, 12mm sides,
           14mm bottom  -  no signature block, so no footer band needed). */
        @page { size: A4 landscape; margin: 14mm 12mm 14mm 12mm; }
        /* DejaVu Sans (embedded TTF) instead of 'Helvetica' (core WinAnsi
           font) so the peso sign U+20B1 has a glyph  -  Helvetica would
           render it as a literal "?". Amounts print with the Settings
           currency code, so no symbol substitution is needed here. */
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #1e293b; }
        h1 { font-size: 18px; margin-bottom: 2px; }
        .subtitle { font-size: 10px; color: #64748b; margin-bottom: 20px; }
        h2 { font-size: 13px; margin: 22px 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 4px; }
        th, td { text-align: left; padding: 5px 8px; border-bottom: 1px solid #e2e8f0; }
        th { background: #f8fafc; font-size: 10px; text-transform: uppercase; letter-spacing: 0.03em; color: #64748b; }
        .overview-grid td { width: 25%; }
        .metric-label { font-size: 9px; color: #64748b; text-transform: uppercase; }
        .metric-note { font-size: 8px; color: #94a3b8; }
        .muted-note { text-transform: none; font-weight: normal; }
        .metric-value { font-size: 15px; font-weight: bold; }
        .trend-up { color: #059669; }
        .trend-down { color: #dc2626; }
        .amount { text-align: right; }
        .empty { color: #94a3b8; font-style: italic; }
        .disclaimer { margin-top: 18px; padding-top: 8px; border-top: 1px solid #e2e8f0; font-size: 8px; color: #94a3b8; }

        /* Corporate letterhead  -  mirrors the browser print header
           (utils/print.js buildHeader): logo + name on the left, title and
           the same labeled meta rows on the right. dompdf has no flexbox, so
           this is a two-cell table. */
        .letterhead { width: 100%; border-bottom: 2px solid #0f2744; padding-bottom: 8px; margin-bottom: 10px; }
        .letterhead td { border: none; padding: 0; vertical-align: top; }
        .letterhead-brand { width: 58%; }
        .letterhead-meta-cell { width: 42%; text-align: right; }
        .letterhead-logo { max-height: 15mm; max-width: 38mm; }
        .letterhead-name { font-size: 13px; font-weight: bold; text-transform: uppercase; color: #0f2744; }
        .letterhead-contact { font-size: 8px; color: #64748b; }
        .doc-title { font-size: 15px; font-weight: bold; color: #111827; }
        .doc-meta-row { font-size: 8px; color: #334155; }
        .doc-meta-label { color: #64748b; }
        .doc-meta-val { color: #111827; }
        .confidential { font-size: 7.5px; color: #b45309; text-transform: uppercase; letter-spacing: 0.04em; }

        /* Repeat column headings after a page break; never split a row. */
        thead { display: table-header-group; }
        tr, .overview-grid td, .card { page-break-inside: avoid; }
    </style>
    @include('pdf.report-style')
</head>
<body>
    @include('pdf.report-footer')
    {{-- Letterhead: same information as the browser print header. --}}
    <table class="letterhead">
        <tr>
            <td class="letterhead-brand">
                @if($company['logo_data_uri'])
                    <img class="letterhead-logo" src="{{ $company['logo_data_uri'] }}" alt="{{ $company['name'] }} logo" />
                @endif
                <div class="letterhead-name">{{ $company['name'] }}</div>
                <div class="letterhead-contact">
                    @if($company['address'])<div>{{ $company['address'] }}</div>@endif
                    @if($company['phone'])<div>Tel: {{ $company['phone'] }}</div>@endif
                    @if($company['email'])<div>{{ $company['email'] }}</div>@endif
                    @if($company['tin'])<div>TIN: {{ $company['tin'] }}</div>@endif
                </div>
            </td>
            <td class="letterhead-meta-cell">
                <div class="doc-title">Financial Dashboard Summary</div>
                <div class="doc-meta-row"><span class="doc-meta-label">Period:</span> <span class="doc-meta-val">Figures for {{ $selected_year }}</span></div>
                <div class="doc-meta-row"><span class="doc-meta-label">Run Date:</span> <span class="doc-meta-val">{{ $generated_at->format('M j, Y, g:i A') }}</span></div>
                @if($generated_by)
                    <div class="doc-meta-row"><span class="doc-meta-label">Generated By:</span> <span class="doc-meta-val">{{ $generated_by }}{{ $generated_by_role ? ' ('.$generated_by_role.')' : '' }}</span></div>
                @endif
                <div class="doc-meta-row"><span class="doc-meta-label">Currency:</span> <span class="doc-meta-val">{{ $currency }}</span></div>
                <div class="confidential">Live snapshot  -  not a financial statement</div>
            </td>
        </tr>
    </table>

    <p class="subtitle">{{ config('app.timezone') }} &middot; figures cover 1 January &ndash; {{ $period_end }}</p>

    <h2>Financial Overview</h2>
    <table class="overview-grid">
        <tr>
            <td>
                <div class="metric-label">Cash Collected <span class="muted-note">({{ $selected_year }})</span></div>
                <div class="metric-value">{{ $currency }} {{ number_format($overview['total_revenue']['value'] ?? 0, 2) }}</div>
                <div class="metric-note">Cash collected via Collections</div>
            </td>
            <td>
                <div class="metric-label">Total Expenses <span class="muted-note">({{ $selected_year }})</span></div>
                <div class="metric-value">{{ $currency }} {{ number_format($overview['total_expenses']['value'] ?? 0, 2) }}</div>
                <div class="metric-note">Posted expense vouchers</div>
            </td>
            <td>
                <div class="metric-label">Available Cash <span class="muted-note">(as of now)</span></div>
                <div class="metric-value">{{ $currency }} {{ number_format($overview['available_cash']['value'] ?? 0, 2) }}</div>
                <div class="metric-note">Point-in-time balance</div>
            </td>
            <td>
                <div class="metric-label">Net Cash Flow <span class="muted-note">({{ $selected_year }})</span></div>
                <div class="metric-value">{{ $currency }} {{ number_format($overview['net_cash_flow']['value'] ?? 0, 2) }}</div>
                <div class="metric-note">Revenue − Expenses</div>
            </td>
        </tr>
    </table>

    <h2>Module Snapshot</h2>
    <table>
        <tr>
            <th>Total Customers</th>
            <th>Total Suppliers</th>
            <th>Active Collectors</th>
            <th>Active Budgets</th>
        </tr>
        <tr>
            <td>{{ $module_cards['total_customers'] ?? 0 }}</td>
            <td>{{ $module_cards['total_suppliers'] ?? 0 }}</td>
            <td>{{ $module_cards['active_collectors'] ?? 0 }}</td>
            <td>{{ $module_cards['active_budgets'] ?? 0 }}</td>
        </tr>
    </table>
    <table>
        <tr>
            <th>Receivable</th>
            <th>Payable</th>
            <th>Collections Today</th>
            <th>Disbursements Today</th>
            <th>Tax Obligations</th>
        </tr>
        <tr>
            <td>{{ $currency }} {{ number_format($module_cards['receivable'] ?? 0, 2) }}</td>
            <td>{{ $currency }} {{ number_format($module_cards['payable'] ?? 0, 2) }}</td>
            <td>{{ $currency }} {{ number_format($module_cards['collections_today'] ?? 0, 2) }}</td>
            <td>{{ $currency }} {{ number_format($module_cards['disbursements_today'] ?? 0, 2) }}</td>
            <td>{{ $currency }} {{ number_format($module_cards['tax_obligations'] ?? 0, 2) }}</td>
        </tr>
    </table>

    <h2>Recent Transactions</h2>
    <p class="subtitle">Showing the latest {{ count($recent_transactions) }} entries, newest first  -  as recorded in the system at the timestamp above.</p>
    @if (count($recent_transactions) === 0)
        <p class="empty">No recent transactions.</p>
    @else
        <table class="transaction-grid">
            <colgroup><col style="width:11%"><col style="width:17%"><col style="width:16%"><col style="width:28%"><col style="width:16%"><col style="width:12%"></colgroup>
            <thead>
            <tr>
                <th style="width:10%">Date</th>
                <th style="width:17%">Reference No.</th>
                <th style="width:16%">Transaction</th>
                <th style="width:27%">Customer / Supplier</th>
                <th class="amount" style="width:18%">Amount</th>
                <th style="width:12%">Status</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($recent_transactions as $t)
                <tr>
                    <td class="nowrap">{{ $t['date'] }}</td>
                    <td>{{ $t['reference'] }}</td>
                    <td>{{ $t['transaction'] }}</td>
                    <td>{{ $t['party'] }}</td>
                    <td class="amount">{{ $currency }} {{ number_format($t['amount'], 2) }}</td>
                    <td>{{ $t['status'] }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif

    <div class="disclaimer">
        This document is a live dashboard snapshot generated for quick reference on
        {{ $generated_at->format('F j, Y \a\t g:i A') }}. It is not a prepared financial
        statement. Amounts reflect records currently in the system and may change as
        transactions are recorded, approved, or amended after this snapshot was taken.
    </div>
    @include('pdf.signatures')
</body>
</html>

