<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Staff Dashboard Summary</title>
    <style>
        @page { size: A4 portrait; margin: 14mm 12mm 14mm 12mm; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #1e293b; }
        h1 { font-size: 18px; margin-bottom: 2px; }
        .subtitle { font-size: 10px; color: #64748b; margin-bottom: 16px; }
        h2 { font-size: 12px; margin: 18px 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; text-transform: uppercase; letter-spacing: 0.04em; color: #0f2744; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 4px; }
        th, td { text-align: left; padding: 5px 8px; border-bottom: 1px solid #e2e8f0; }
        th { background: #f8fafc; font-size: 9px; text-transform: uppercase; letter-spacing: 0.03em; color: #64748b; }
        .overview-grid td { width: 20%; vertical-align: top; background: #f8fafc; border: 1px solid #e2e8f0; padding: 8px; }
        .metric-label { font-size: 8.5px; color: #64748b; text-transform: uppercase; font-weight: 600; margin-bottom: 4px; }
        .metric-value { font-size: 14px; font-weight: bold; color: #0f2744; }
        .amount { text-align: right; }
        .empty { color: #94a3b8; font-style: italic; text-align: center; padding: 12px; }
        .badge { display: inline-block; padding: 2px 6px; font-size: 8px; font-weight: bold; border-radius: 4px; }
        .badge-amber { background: #fef3c7; color: #92400e; }
        .disclaimer { margin-top: 20px; padding-top: 8px; border-top: 1px solid #e2e8f0; font-size: 8px; color: #94a3b8; }

        .letterhead { width: 100%; border-bottom: 2px solid #0f2744; padding-bottom: 8px; margin-bottom: 10px; }
        .letterhead td { border: none; padding: 0; vertical-align: top; }
        .letterhead-brand { width: 55%; }
        .letterhead-meta-cell { width: 45%; text-align: right; }
        .letterhead-logo { max-height: 15mm; max-width: 38mm; }
        .letterhead-name { font-size: 13px; font-weight: bold; text-transform: uppercase; color: #0f2744; }
        .letterhead-contact { font-size: 8px; color: #64748b; }
        .doc-title { font-size: 15px; font-weight: bold; color: #111827; }
        .doc-meta-row { font-size: 8px; color: #334155; }
        .doc-meta-label { color: #64748b; }
        .doc-meta-val { color: #111827; }
        .confidential { font-size: 7.5px; color: #b45309; text-transform: uppercase; letter-spacing: 0.04em; }

        thead { display: table-header-group; }
        tr, .overview-grid td { page-break-inside: avoid; }
    </style>
</head>
<body>
    <table class="letterhead">
        <tr>
            <td class="letterhead-brand">
                @if($company['logo_data_uri'])
                    <img class="letterhead-logo" src="{{ $company['logo_data_uri'] }}" alt="{{ $company['name'] }} logo" />
                @endif
                <div class="letterhead-name">{{ $company['name'] }}</div>
                <div class="letterhead-contact">
                    @if($company['address'])<div>{{ $company['address'] }}</div>@endif
                    @if($company['phone'])<div>Tel: {{ $company['phone'] }}</div>@endif
                    @if($company['email'])<div>{{ $company['email'] }}</div>@endif
                    @if($company['tin'])<div>TIN: {{ $company['tin'] }}</div>@endif
                </div>
            </td>
            <td class="letterhead-meta-cell">
                <div class="doc-title">Staff Dashboard Summary</div>
                <div class="doc-meta-row"><span class="doc-meta-label">Run Date:</span> <span class="doc-meta-val">{{ $generated_at->format('M j, Y, g:i A') }}</span></div>
                @if($generated_by)
                    <div class="doc-meta-row"><span class="doc-meta-label">Generated By:</span> <span class="doc-meta-val">{{ $generated_by }}{{ $generated_by_role ? ' ('.$generated_by_role.')' : '' }}</span></div>
                @endif
                <div class="doc-meta-row"><span class="doc-meta-label">Currency:</span> <span class="doc-meta-val">{{ $currency }}</span></div>
                <div class="confidential">Operational Staff Report &middot; Internal Use Only</div>
            </td>
        </tr>
    </table>

    <p class="subtitle">{{ config('app.timezone') }} &middot; Snapshot generated on {{ $generated_at->format('F j, Y') }}</p>

    <h2>Operational Summary</h2>
    <table class="overview-grid">
        <tr>
            <td>
                <div class="metric-label">Customers</div>
                <div class="metric-value">{{ number_format($summary['customers'] ?? 0) }}</div>
            </td>
            <td>
                <div class="metric-label">Suppliers</div>
                <div class="metric-value">{{ number_format($summary['suppliers'] ?? 0) }}</div>
            </td>
            <td>
                <div class="metric-label">AR Outstanding</div>
                <div class="metric-value">{{ $currency }} {{ number_format($summary['ar_outstanding'] ?? 0, 2) }}</div>
            </td>
            <td>
                <div class="metric-label">AP Outstanding</div>
                <div class="metric-value">{{ $currency }} {{ number_format($summary['ap_outstanding'] ?? 0, 2) }}</div>
            </td>
            <td>
                <div class="metric-label">Expenses This Month</div>
                <div class="metric-value">{{ $currency }} {{ number_format($summary['expenses_this_month'] ?? 0, 2) }}</div>
            </td>
        </tr>
    </table>

    <h2>Items Requiring Attention</h2>
    <table style="margin-bottom: 12px;">
        <thead>
            <tr>
                <th style="width: 22%;">Category</th>
                <th style="width: 38%;">Item / Reference</th>
                <th style="width: 22%;">Status / Details</th>
                <th style="width: 18%; text-align: right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            @php $hasAttention = false; @endphp

            @foreach($attention['ar'] ?? [] as $item)
                @php $hasAttention = true; @endphp
                <tr>
                    <td><strong>AR Overdue</strong></td>
                    <td>{{ $item['customer_name'] ?? '—' }} ({{ $item['invoice_number'] ?? '—' }})</td>
                    <td>Due: {{ !empty($item['due_date']) ? \Carbon\Carbon::parse($item['due_date'])->format('M j, Y') : '—' }}</td>
                    <td class="amount">{{ $currency }} {{ number_format($item['amount'] ?? 0, 2) }}</td>
                </tr>
            @endforeach

            @foreach($attention['ap'] ?? [] as $item)
                @php $hasAttention = true; @endphp
                <tr>
                    <td><strong>AP Pending Approval</strong></td>
                    <td>{{ $item['supplier_name'] ?? '—' }} ({{ $item['invoice_number'] ?? '—' }})</td>
                    <td>Due: {{ !empty($item['due_date']) ? \Carbon\Carbon::parse($item['due_date'])->format('M j, Y') : '—' }}</td>
                    <td class="amount">{{ $currency }} {{ number_format($item['amount'] ?? 0, 2) }}</td>
                </tr>
            @endforeach

            @foreach($attention['expenses'] ?? [] as $item)
                @php $hasAttention = true; @endphp
                <tr>
                    <td><strong>Expense Pending</strong></td>
                    <td>{{ $item['title'] ?? '—' }} ({{ $item['expense_number'] ?? '—' }})</td>
                    <td>Date: {{ !empty($item['date']) ? \Carbon\Carbon::parse($item['date'])->format('M j, Y') : '—' }}</td>
                    <td class="amount">{{ $currency }} {{ number_format($item['amount'] ?? 0, 2) }}</td>
                </tr>
            @endforeach

            @foreach($attention['disbursements'] ?? [] as $item)
                @php $hasAttention = true; @endphp
                <tr>
                    <td><strong>Disbursement Pending</strong></td>
                    <td>Disbursed To: {{ $item['payee'] ?? '—' }} ({{ $item['voucher_number'] ?? '—' }})</td>
                    <td>Date: {{ !empty($item['date']) ? \Carbon\Carbon::parse($item['date'])->format('M j, Y') : '—' }}</td>
                    <td class="amount">{{ $currency }} {{ number_format($item['amount'] ?? 0, 2) }}</td>
                </tr>
            @endforeach

            @foreach($attention['budgets'] ?? [] as $item)
                @php $hasAttention = true; @endphp
                <tr>
                    <td><strong>Budget Missing Plan</strong></td>
                    <td>{{ $item['title'] ?? '—' }} (FY {{ $item['fiscal_year'] ?? '—' }})</td>
                    <td><span class="badge badge-amber">No Plan Uploaded</span></td>
                    <td class="amount">{{ $currency }} {{ number_format($item['allocated_amount'] ?? 0, 2) }}</td>
                </tr>
            @endforeach

            @if(!$hasAttention)
                <tr>
                    <td colspan="4" class="empty">No items currently require follow-up or approval.</td>
                </tr>
            @endif
        </tbody>
    </table>

    <h2>Recent Operational Activity</h2>
    <table>
        <thead>
            <tr>
                <th style="width: 20%;">Date &amp; Time</th>
                <th style="width: 18%;">User</th>
                <th style="width: 17%;">Module</th>
                <th style="width: 45%;">Description</th>
            </tr>
        </thead>
        <tbody>
            @forelse($recent_activity ?? [] as $act)
                <tr>
                    <td>{{ !empty($act['time']) ? \Carbon\Carbon::parse($act['time'])->format('M j, Y g:i A') : '—' }}</td>
                    <td>{{ $act['user_name'] ?? 'System' }}</td>
                    <td>{{ $act['module'] ?? '—' }}</td>
                    <td>{{ $act['description'] ?? '—' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" class="empty">No recent activity recorded.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="disclaimer">
        This document is an internal operational summary generated automatically by {{ config('app.name', 'Financial Management System') }}.
        Figures are live as of the run time printed above.
    </div>
</body>
</html>
